name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Installation dependancies
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install NPM
        run: npm ci

      # Build
      - name: Build
        run: |
          npm run build
          npm run test
          
      # Move build to github-page branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
